---
geometry: 
  margin=1.0in
fontsize: 12pt 
lang: en
header-includes:
- \usepackage{soul}
- \renewcommand*\familydefault{\sfdefault}
- \usepackage{setspace}
- \usepackage[left]{lineno}
- \linenumbers
---

# Surviving climate change: Understanding the facultative CAM photosynthesis in *Pereskia aculeata* plants

**Runing title:** Facultative CAM photosynthesis in *Pereskia aculeata*

Luanna Costa Cenciareli${^1}$; Moni Soares Justi${^1}$; Sérgio Luiz Ferreira da Silva${^2}$; João Paulo Alves de Barros${^2}$; Milton C. Lima Neto${^1}{^\star}$

${^1}$Institute of Biosciences, Coastal Campus,State University of São Paulo - UNESP. São Vicente, SP, Brazil. ${^2}$Academic Unity of Serra Talhada, Federal Rural University of Pernambuco - UFRPE, Serra Talhada, PE, Brazil.

${^\star}$To whom correspondence should be addressed: \href{mailto:milton.lima-neto@unesp.br}{milton.lima-neto@unesp.br} Institute of Biosciences, Coastal Campus. State University of São Paulo, P.O Box: 73601/SP ZIPCODE: 11380-972. São Vicente, SP, Brazil.

\vspace{2mm}

## Abstract

Keywords:

Abbreviations: $\psi_w$ - water potential, PPFD - photosynthetic photon flux density, PVPP - polivinilpolipirrolidone, rcf - relative centrifuge force, TBARS - thiobarbituric acid reactive substances;

\newpage

## Introduction

Climate change has a significant impact on global plant biodiversity and food security, with increasing temperatures, droughts, and extreme weather events posing challenges to plant growth and crop production [@fenollosa_physiological_2019]. These changes threaten to reduce crop yields and disturb ecosystems, resulting in an increased risk of food insecurity and harm to communities worldwide. Therefore, it is essential to better comprehend the impacts of global warming on plant biodiversity and food security and to develop effective strategies for mitigating these effects, ensuring agriculture and natural ecosystems have a sustainable future [@rosenzweig_assessing_2014]. Changes in development patterns, including flowering and fruiting periods, as well as increased susceptibility to parasites and diseases, are among the diverse effects of climate change on plants.

Climate change is leading to a harsher and drier planet, and as a result, the demand for water in agriculture is expected to double by 2050, while the availability of fresh water is projected to decrease by 50% [@gupta_physiology_2020]. Drought alone causes more annual losses in crop yield than all pathogens combined [@gupta_physiology_2020]. Water is essential for plant survival, and water deficits reduce plant growth. Drought is a common effect of climate change that negatively impacts plant productivity and growth by disrupting the energy balance between the capacity to absorb and use light energy during photosynthesis. It damages the physiological metabolism and photosynthesis of plants, ultimately reducing crop production. C3 plants typically close stomata under drought conditions to avoid water loss, decreasing $CO_2$ assimilation [@lawson_speedy_2019]. Since the Calvin-Benson-Bassham cycle is one of the primary electron sinks of photosynthetic electron transport, stomatal limitations can upset the delicate balance between the production and consumption of reducing equivalents such as $Fd_{red}$, ATP, and NADPH, producing excess energy in chloroplasts [@lima_neto_regulation_2017]. This imbalance disrupts the redox equilibrium in the chloroplast, thereby altering the reactive oxygen species (ROS) processing and signaling systems [@foyer_reactive_2018].

Plants have strategies to prevent water loss, including but not limited to closing stomata and developing deeper roots [@chaves_understanding_2003]. However, there is still much work to be done to produce crops that can thrive in a changing climate. Plant breeding and biotechnology are key areas where progress can be made to develop crops that are more resilient and adaptable to changing environmental conditions such as heat and drought stress [@gupta_physiology_2020]. One potential adaptation strategy for plants to cope with the challenges of climate change is crassulacean acid metabolism (CAM), a unique type of photosynthesis that improves water-use efficiency (WUE) and drought tolerance [@luttge_ecophysiology_2004]. CAM is a distinctive photosynthetic pathway that has evolved in plants growing in arid and semi-arid environments.

CAM plants have adapted to water-limited conditions by fixing $CO_2$ at night when the stomata are open, storing it as organic acids, and releasing it during the day when the stomata are closed [@luttge_ecophysiology_2004]. This process, known as obligate CAM, is characterized by the strict separation of day and night metabolic activities. In Phase I, which occurs during the dark period, $CO_2$ is fixed by phosphoenolpyruvate carboxylase (PEPC) to form malate, which is then accumulated in the vacuole. In Phase II there is a transition from nocturnal to daytime conditions. The stomata remain open for a short time during the very early light period, then close as malic acid is decarboxylated to release $CO_2$ for photosynthesis. During Phase III, the stomata close completely, and the stored malate is transported out of the vacuole. The malate is then decarboxylated to release $CO_2$, which is assimilated via Calvin-Benson-Bassham (CBB) cycle reactions. In Phase IV, the transition from daytime to nocturnal conditions occurs. When the malate supply is exhausted in the late afternoon, the stomata reopen for $CO_2$ uptake with direct assimilation [@luttge_ecophysiology_2004]

The expression of CAM phases is plastic, affecting CAM terminology and definitions [@luttge_ecophysiology_2004]. First, CAM-idling, often seen under extreme drought conditions, involves nocturnal acid accumulation without daytime decarboxylation, essentially a "survival mode", where stomata remain closed day and night, and the organic cycle is fed by internal recycling of nocturnaly refixed respiratory $CO_2$. CAM-cycling, where stomata remain closed during the dark period with some minor synthesis of organic acid fed by respiratory $CO_2$. Stomata are open during the light period, with uptake of atmospheric $CO_2$ and direct assimilation of CBB reactions in addition to the assimilation of remobilized $CO_2$ from noctunarly stored organic acid [@luttge_ecophysiology_2004]. Finally, facultative CAM allows a dynamic switch between $C_3$ and CAM modes depending on environmental conditions [@winter_ecophysiology_2019, @winter_facultative_2014].

The different species may present various forms of CAM and may also be expressed temporarily in a given species, constituting different CAM physiotypes [@winter_facultative_2014]. Despite the significance of CAM metabolism, its regulation, molecular basis, and evolution, as well as the mechanisms underlying mesophyll conductance and the regulation of photosynthetic electron transport in these plants, are not completely understood [@cousins_recent_2020]. Moreover, a comprehensive and coherent definition of CAM is not straightforward. Thus, understanding the physiological mechanisms underlying CAM photosynthesis is essential for developing strategies to improve crop productivity in water-limited environments and for predicting the responses of natural ecosystems to climate change.

*Pereskia aculeata* Mill., also known as ora-pro-nobis or Barbados gooseberry, is a highly nutritious leafy plant species from the Cactaceae family, subfamily Pereskioideae. It is an edible plant commonly found in the Brazilian Atlantic Forest and is known for its high mineral and protein contents [@queiroz_growing_2015]. *P. aculeata* is a hardy and perennial plant that can grow well in various soil types. In contrast to other Pereskia species, which are shrubs or trees, *P. aculeata* is classified as a liana (woody vine) owing to its semi-scandent growth form [@venter_interactive_2022]. It is becoming a problematic invasive alien plant in South Africa, occurring in high densities, smothering native trees and shrubs, competing for resources, and ultimately causing the demise of the affected vegetation [@venter_interactive_2022].

While most Cactaceae species use the obligate CAM photosynthetic pathway [@luttge_ecophysiology_2004], @nobel_droughtinduced_1987\], *P. aculeata* is apparently capable of facultative CAM-cycling [@martin_photosynthetic_2000], and drought-induced CAM-idling [@edwards_ecological_2006-1]. However, this interpretation is controversial in the literature and more research is required. Despite @nobel_droughtinduced_1987 showing that drought stress served only to reduce daytime $CO_2$ uptake rates, with no nighttime uptake induced in *P. aculeata*, the authors did not measure changes in leaf acidity. In the research of @rayder_carbon_1981, they reported substantial diel changes in acidity of the leaves of well-watered and drought-stressed *P. aculeata* plants. Considering the lack of information on the regulation and induction of facultative CAM photosynthesis, the aim of our study was to evaluate the influence of drought on the dynamics of CAM metabolism in *P. aculeata* plants. In particular, we were interested in how *P. aculeata* adjust the components associated with the light-dark patterns of light energy use, the regulation of photosynthetic quantum yields, and photoprotective mechanisms.

## Material and methods

### Plant material and growth conditions

*Pereskia aculeata* plants were propagated from cuttings in 15 L plastic pots, using a 1:1 (v/v) mixture of washed sand and commercial substrate. They were maintained under greenhouse conditions at the Institute of Biosciences, São Paulo State University, São Vicente, Brazil. The plants were watered daily to pot capacity and supplemented weekly with a half-strength Hoagland and Arnon nutrient solution [@hoagland_water_1950]. After three months, when the plants were well-established and growing vigorously, they were divided into two groups. The first group continued to be watered daily to pot capacity (control), while the second group was watered with only 30% of the volume used to achieve pot capacity (drought). Water-stressed plants showed visible wilting and chlorosis at the time of experimentation. At this point, plants were harvested for future analysis. One group of plants was kept under control conditions, while another group that had been exposed to 90 days of drought was re-watered to pot capacity for 7 days (recovery). After the recovery period, plants were harvested for future analysis. Five plants were used for each treatment (control, drought, control after recovery and recovery). An experimental unit was represented by one plant in 15 L plastic pot.

### Relative water content, membrane damage and water potential

After harvesting, the total aboveground fresh matter (FM) of each plant was determined. The relative water content (RWC) was assessed from leaf samples immediately weighted and harvested (FM), followed by rehydration in distilled water for 24 h in the dark (turgid mass. TM), and transferred to an oven at $60^o C$ until constant weight (dry weight, DM). The relative water content was calculated according to @lima_neto_jatropha_2015 by the equation: $$\frac{(FM - DM)} {(TM - DM)} \cdot 100$$

The membrane damage measured by electrolyte leakage was assessed as described previously [@lima_neto_regulation_2017]. Leaf segments were placed in test tubes containing 10 mL of deionized water and incubated for 24 h in a shaking water bath. After that, the electric conductivity of the medium was evaluated $(L_1)$. Then, the segments were boiled for 1 h, cooled down to ambient temperature in an ice bath, and measured the electric conductivity $(L_2)$. The membrane damage (MD) was calculated as $MD=\left(\frac{L_1} {L_2}\right) \cdot 100$ and expressed in %.

The leaf predawn water potential $(\psi_w)$ was evaluated using a pressure chamber (3000 Scholander PWSC, ICT, International, Armidale, AUS) [@scholander_sap_1960]. Due to the very short petiole, a fresh leaf as wrapped in Parafilm and then excised a small amount of mesophyll surrounding the mid-vein to fit the leaf into the chamber lid. This adapted method has an artifact with reading consistently about 0.1 - 0.2 MPa less negative, see @edwards_ecological_2006-1 .

### Lipid peroxidation and hydrogen peroxide content

The lipid peroxidation was assessed based on the formation of thiobarbituric acid reactive substances (TBARS). TBARS concentration was calculated using its absorption coefficient $(155\; mM^{-1} \; cm^{-1})$ and expressed as $nmol\; MDA-TBA\; g^{-1}\; FM)$ [@Cakmak1991]. The $H_2O_2$ content was determined by the Amplex Red oxidation method. Leaf segments were ground in a $K^+$ phosphate buffer 100 mM, pH 7.5. The crude extract was centrifuged at 12,000 rcf for 30 minutes at $4^o C$. Acoording to the manufacturer protocol, the supernatant was supplemented with 10 mM Amplex-Red and 10 U of horseradish peroxidase. The resorufin production was measured at 560 nm in a spectrophotometer [@zhou_stable_1997].

### Gas exchange and chlorophyll fluorescence

Gas exchange parameters were measured using an infrared gas analyzer (IRGA LI 6400 XT, LiCOR, Lincoln, NE, USA), with a leaf chamber fluorometer attached (LI-6400-40, LICOR, Lincoln, NE, USA), on the second fully expanded leaf. During the measurements, the conditions inside the IRGA chamber were controlled to PPFD of 800 $\mu mol\;m^{2}\;s^{-1}$, air $CO_2$ partial pressure of 380 $\mu mol \; mol^{-1}$, air vapor pressure deficit (VPD) or 1.0 $\pm$ 0.5 kPa and air temperature of $25^o C$. The amount of blue light was set to 10% of PPFD to maximize stomatal aperture [@ziotti_photorespiration_2019]. Gas exchange was measured after at least 30 minutes of light exposure to achieve steady-state photosynthesis after photosynthetic induction.

Chlorophyll *a* fluorescence was measured using the saturation pulse method with a portable chlorophyll fluorometer (JR-PAMIII WALZ, Effeltrich, Germany). Leaves were dark-adapted for 30 min for assessing Fo and Fm. Then, the leaves were exposed to actinic light $(500\; \mu mol\; m^2\; s^{-1})$ for at least 30 min to reach a photosynthetic steady state. The actinic light used was near the saturation PPFD observed from previous light curves performed in our laboratory. The intensity and duration of the saturation pulses were $8,000\; \mu mol\; m^2\; s^{-1}$ and 0.7 s, respectively. The following parameters were assessed: the potential quantum yield of PSII $[Fv/Fm = (Fm-Fo)/Fm]$; the effective quantum yield of PSII $[YII = (Fm'- Fs)/Fm']$, the proportion of opened $(qP)$ and closed $(1-qP)$ PSII states, the non-photochemical quenching $[NPQ = (Fm – Fm')/Fm']$, the quantum yield of non-regulated nonphotochemical energy loss in PSII $[Y(NO) = F/Fm]$ and the quantum yield of regulated non-photochemical energy loss in PSII $[Y(NPQ) = F/ Fm' - F/Fm]$. $Fm$ and $Fo$ are the maximum and minimum fluorescence of dark-adapted leaves, respectively; $Fm′$ and $Fs$ are the maximum and steady state fluorescence in the light-adapted samples [@maxwell_chlorophyll_2000].

### Acid titrations and pigment contents

Leaf samples were collected in triplicate. The main vein was avoided and the leaf blade was frozen until assayed. The plant material was sampled before dawn and after dusk at the end of the experiment. Individual samples were ground in distilled water with a mortar and pestle. They were then tritated with 0.01 N KOH using phenolphthalein solution as indicator. Data are expressed as $\mu eq\; acid\; g\; FM^{-1}$ [@rayder_carbon_1981].

Leaf segments were sampled and extracted in the dark at $8^oC$ for 8h in cold 80% acetone solution. Then, the samples were centrifuged at 10,000 rcf for 5 min. The supernatant was read in a spectrophotometer at different wavelengths as previously described [@lichtenthaler_determination_1983]. The total anthocyanin content was determined as previously described by @silva_plasticity_2023. Leaf segments were extracted in methanol and 1% HCl at 4°C overnight. Subsequently, chloroform was added to the homogenate, which was then centrifuged at 14,000 rcf for 5 min. The upper fraction was used for spectrophotometric reading at 530 nm and 657 nm. The total anthocyanin content was expressed as A530 - A657 $g^-1$ FW.

### Protein extraction and enzymatic assays

Leaf samples (1 g) were harvested and extracted in a cold mortar and pestle with liquid $N_2$ and 9 mL of the extraction medium consisting of 100 mM Hepes-NaOH (pH 7.5), 2 mM $MgCl_2$, 2 mM EDTA, and 10 mM DTT. PVPP (0.5 g) was added before grinding each sample to aid mucilage removal. The homogenate was squeezed through one layer of Miracloth. The extract was centrifuged at 14,000 rcf at $4^oC$ for 20 min before being passed through a small Sephadex G-25 column previously equilibrated with extraction buffer adjusted to pH 7.5. The extraction method was adapted from a previous work of @rayder_carbon_1981.

The ascorbate peroxidase (APX - E.C. 1.11.1.11) activity was assayed in a reaction mixture containing 0.5 mM ascorbate and 0.1 mM EDTA dissolved in 100 mM K-phosphate buffer (pH 7.0) and the enzyme extract. The reaction was started by adding 30 mM $H_2O_2$. The enzymatic activity was measured following the decrease in absorbance at 290 nm and $25^o C$, over 300 s, and expressed as $(\mu mol\; ascorbate\; mg^{-1}\; protein\; min^{-1} )$ [@nakano_hydrogen_1981]. Superoxide dismutase (SOD E.C. 1.15.1.1) was determined by the nitroblue tetrazolium chloride (NBT) photoreduction. SOD activity was measured by adding the leaf extrect to a mixture containing 50 mM K-phosphate buffer (pH 7.8), 0.1 mM EDTA, 13 mM L-methionine, 2 $\mu M$ riboflavin, and 75 $\mu M$ p-NBT in the dark. The reaction was carried out under illumination (30 W fluorescent lamp) at $25^o C$ for 6 minutes. The absorbance was measured at 540 nm [@giannopolotis_superoxide_1977]. One unit of SOD activity was defined as the amount of enzyme required to inhibit 50 % of the NBT photoreduction, and activity was expressed as $U\; mg\; protein\; min^{-1}$. Catalase (CAT E.C. 1.11.1.6) was measured following the oxidation of $H_2O_2$ at 240 nm. CAT activity was determined by the reaction of the crude enzyme extract in 50 mM K-buffer (pH 7.0) containing 20 mM $H_2O_2$. The absorbance at 240 nm was measured over 300 s [@havir_biochemical_1987], and CAT activity was calculated according to the molar extinction coefficient of $H_2O_2$ $(36\; mM\; cm^{-1})$ and expressed as $(\mu mol \; H_2O_2\; mg^{-1}\; protein\; min^{-1})$.

### Statistical analysis

One factor, two factor, PCA and Network analysis

## Results

## Discussion

-   Briefly synthesize results

"This combination of CAM-like acid fluctuations with C3 gas exchange is characteristic of CAM-cycling, albeit at low levels in these pereskioids. Whether or not diel acid fluctuations or even CAM gas exchange might be stimulated in these or the other species by drought stress was not examined in this study." [@martin_photosynthetic_2000].

@queiroz_growing_2015 propose the use of intermittent drought conditions to encourage higher leaf area and photosynthetic efficiency in *P. aculeata*.

Therefore, further research is needed to understand the CAM photosynthesis in *P. aculeata* plants and its potential role in helping the species to survive in changing environmental conditions caused by climate change.

## Conclusion

## Ackonwledgments

\clearpage

## References

::: {#refs}
:::

\newpage

## Tables

## Figures

**Figure 1.** The caption of figure 1

\newpage

**Figure 2.** The caption of figure 2
